const productlist = [
    {
        id: '1',
        img: 'assets/images/products/img-10.png',
        rating:'4.9',
        title: "World's most expensive t shirt",
        content: 'T-Shirt house best black boys T-Shirt fully cotton material & all size available hirt fully cotton material & all size available.',
        price: '266.24',
        mrp: '354.99',
        stock: '12',
        color: ['secondary', 'light', 'dark'],
        size: ['S', 'M', 'L'],
        discount: '25%',
        type: 'fashion',
        orders: '48',
        publish:'12 Oct, 2021'
    },
    {
        id: '2',
        img: 'assets/images/products/img-15.png',
        rating:'4.2',
        title: "Like Style Women Black Handbag",
        content: 'T-Shirt house best black boys T-Shirt fully cotton material & all size available hirt fully cotton material & all size available.',
        price: '742.00',
        stock: '06',
        color: ['light', 'dark'],
        type: 'fashion',
        orders:'30',
        publish:'06 Jan, 2021'
    },
    {
        id: '3',
        img: 'assets/images/products/img-1.png',
        rating:'3.8',
        title: "Black Horn Backpack For Men Bags 30 L Backpack",
        content: 'T-Shirt house best black boys T-Shirt fully cotton material & all size available hirt fully cotton material & all size available.',
        price: '113.24',
        mrp: '150.99',
        stock: '10',
        color: ['primary', 'danger', 'secondary'],
        size: ['S', 'M', 'L'],
        discount:'25%',
        type:'grocery',
        orders:'48',
        publish:'26 Mar, 2021'
    },
    {
        id: '4',
        img: 'assets/images/products/img-7.png',
        rating:'4.7',
        title: "Innovative education book",
        content: 'T-Shirt house best black boys T-Shirt fully cotton material & all size available hirt fully cotton material & all size available.',
        price: '96.26',
        stock: '15',
        type:'kids',
        orders:'40',
        publish:'19 Apr, 2021'
    },
    {
        id: '5',
        img: 'assets/images/products/img-4.png',
        rating:'4.7',
        title: "Sangria Girls Mint Green & Off-White Solid Open Toe Flats",
        content: 'T-Shirt house best black boys T-Shirt fully cotton material & all size available hirt fully cotton material & all size available.',
        price: '24.07',
        mrp: '96.26',
        stock: '08',
        color: ['success', 'danger', 'secondary'],
        size: ['40', '41', '42'],
        discount:'75%',
        type:'kids',
        orders:'55',
        publish:'30 Mar, 2021'
    },
    {
        id: '6',
        img: 'assets/images/products/img-5.png',
        rating:'4.0',
        title: "Lace-Up Casual Shoes For Men",
        content: 'T-Shirt house best black boys T-Shirt fully cotton material & all size available hirt fully cotton material & all size available.',
        price: '229.00',
        stock: '15',
        color: ['danger'],
        size: ['40', '41', '42'],
        type:'fashion',
        orders:'48',
        publish:'12 Oct, 2021'
    },
    {
        id: '7',
        img: 'assets/images/products/img-6.png',
        rating:'4.8',
        title: "Striped High Neck Casual Men Orange Sweater",
        content: 'T-Shirt house best black boys T-Shirt fully cotton material & all size available hirt fully cotton material & all size available.',
        price: '62.40',
        mrp: '120.00',
        stock: '12',
        size: ['S', 'M', 'L','XL'],
        discount:'48%',
        type:'fashion',
        orders:'45',
        publish:'15 May, 2021'
    },
    {
        id: '8',
        img: 'assets/images/products/img-9.png',
        rating:'2.4',
        title: "Lace-Up Casual Shoes For Men",
        content: 'T-Shirt house best black boys T-Shirt fully cotton material & all size available hirt fully cotton material & all size available.',
        price: '194.65',
        mrp: '229.00',
        stock: '20',
        color: ['light', 'warning'],
        size: ['S', 'L'],
        discount:'15%',
        type:'kids',
        orders:'48',
        publish:'21 Jun, 2021'
    },
    {
        id: '9',
        img: 'assets/images/products/img-10.png',
        rating:'4.9',
        title: "Printed, Typography Men Round Neck Black T-shirt",
        content: 'T-Shirt house best black boys T-Shirt fully cotton material & all size available hirt fully cotton material & all size available.',
        price: '81.99',
        stock: '14',
        color: ['dark', 'light'],
        size: ['S','M','L','XL'],
        type:'fashion',
        orders:'55',
        publish:'15 Jan, 2021'
    },
    {
        id: '10',
        img: 'assets/images/products/img-12.png',
        rating:'4.1',
        title: "Carven Lounge Chair Red",
        content: 'T-Shirt house best black boys T-Shirt fully cotton material & all size available hirt fully cotton material & all size available.',
        price: '209.99',
        stock: '20',
        color: ['secondary', 'dark','danger','light'],
        type:'furniture',
        orders:'60',
        publish:'15 Jun, 2021'
    },
    {
        id: '11',
        img: 'assets/images/products/img-3.png',
        rating:'3.5',
        title: "Ninja Pro Max Smartwatch",
        content: 'T-Shirt house best black boys T-Shirt fully cotton material & all size available hirt fully cotton material & all size available.',
        price: '247.27',
        mrp: '309.09',
        stock: '12',
        color: ['secondary', 'info'],
        discount:'20%',
        type:'watches',
        orders:'48',
        publish:'12 Oct, 2021'
    },
    {
        id: '12',
        img: 'assets/images/products/img-2.png',
        rating:'4.1',
        title: "Opinion Striped Round Neck Green T-shirt",
        content: 'T-Shirt house best black boys T-Shirt fully cotton material & all size available hirt fully cotton material & all size available.',
        price: '126.99',
        stock: '06',
        color: ['success'],
        size: ['S','M','L','XL'],
        type:'fashion',
        orders:'30',
        publish:'06 Jan, 2021'
    }
]

export { productlist}