const transaction = [

    {
        "id": 1,
        "type": "down",
        "transactionID": "#TBSC320002830",
        "amount": "$253.32",
        "img": "assets/images/ecommerce/payment/american-express.png",
        "paymentMethod": "American Express",
        "transactionDate": "15 Jan, 2023",
        "status": "Successful",
        "clientName": "Diana Nichols",
        "clientEmail": "diana@toner.com",
        "vatId": "TB211145424",
        "icon": "bx-trending-down",
        "color": "danger"
    },
    {
        "id": 2,
        "type": "up",
        "transactionID": "#TBSC320002836",
        "amount": "$745.00",
        "img": "assets/images/ecommerce/payment/paypal.png",
        "paymentMethod": "PayPal",
        "transactionDate": "19 Jan, 2023",
        "status": "Denied",
        "clientName": "Valentine Morin",
        "clientEmail": "euismod.enim@outlook.net",
        "vatId": "TB211145425",
        "icon": "bx-trending-up",
        "color": "success"
    },
    {
        "id": 3,
        "type": "down",
        "transactionID": "#TBSC320002645",
        "amount": "$2,145.87",
        "img": "assets/images/ecommerce/payment/discover.png",
        "paymentMethod": "Discover",
        "transactionDate": "01 Nov, 2022",
        "status": "Successful",
        "clientName": "Brody Holman",
        "clientEmail": "metus@protonmail.org",
        "vatId": "TB211155424",
        "icon": "bx-trending-up",
        "color": "success"
    },

    {
        "id": 4,
        "type": "up",
        "transactionID": "#TBSC320002930",
        "amount": "$985.00",
        "img": "assets/images/ecommerce/payment/paypal.png",
        "paymentMethod": "PayPal",
        "transactionDate": "20 Jan, 2023",
        "status": "Pending",
        "clientName": "Jolie Hood",
        "clientEmail": "nunc.nulla@yahoo.edu",
        "vatId": "TB211145524",
        "icon": "bx-trending-down",
        "color": "danger"
    },
    {
        "id": 5,
        "type": "up",
        "transactionID": "#TBSC320002987",
        "amount": "$3654.32",
        "img": "assets/images/ecommerce/payment/american-express.png",
        "paymentMethod": "American Express",
        "transactionDate": "29 Feb, 2023",
        "status": "Successful",
        "clientName": "Buckminster Wong",
        "clientEmail": "dictum.phasellus.in@hotmail.org",
        "vatId": "TB211545424",
        "icon": "bx-trending-down",
        "color": "danger"
    },
    {
        "id": 6,
        "type": "down",
        "transactionID": "#TBSC320003001",
        "amount": "$654.02",
        "img": "assets/images/ecommerce/payment/visa.png",
        "paymentMethod": "Visa Credit/Debit",
        "transactionDate": "24 Mar, 2023",
        "status": "Denied",
        "clientName": "Howard Lyons",
        "clientEmail": "neque.sed.dictum@icloud.org",
        "vatId": "TB251145424",
        "icon": "bx-trending-down",
        "color": "danger"
    },
    {
        "id": 7,
        "type": "down",
        "transactionID": "#TBSC320003203",
        "amount": "$745.02",
        "img": "assets/images/ecommerce/payment/discover.png",
        "paymentMethod": "Discover",
        "transactionDate": "07 Jan, 2023",
        "status": "Pending",
        "clientName": "Howard Oneal",
        "clientEmail": "porttitor.tellus.non@yahoo.net",
        "vatId": "TB211146424",
        "icon": "bx-trending-up",
        "color": "success"
    },
    {
        "id": 8,
        "type": "down",
        "transactionID": "#TBSC320002830",
        "amount": "$3654.19",
        "img": "assets/images/ecommerce/payment/american-express.png",
        "paymentMethod": "American Express",
        "transactionDate": "09 May, 2022",
        "status": "Denied",
        "clientName": "Jena Hall",
        "clientEmail": "lectus.sit.amet@protonmail.edu",
        "vatId": "TB211165424",
        "icon": "bx-trending-down",
        "color": "danger"
    },

    {
        "id": 9,
        "type": "up",
        "transactionID": "#TBSC320003319",
        "amount": "$874.31",
        "img": "assets/images/ecommerce/payment/american-express.png",
        "paymentMethod": "American Express",
        "transactionDate": "17 Sep,, 2022",
        "status": "Successful",
        "clientName": "Paki Edwards",
        "clientEmail": "edwards.phasellus.in@hotmail.org",
        "vatId": "TB211145467"
    },
    {
        "id": 10,
        "type": "up",
        "transactionID": "#TBSC320003369",
        "amount": "$261.00",
        "img": "assets/images/ecommerce/payment/paypal.png",
        "paymentMethod": "PayPal",
        "transactionDate": "15 Jan, 2023",
        "status": "Successful",
        "clientName": "Nell Potter",
        "clientEmail": "nella@toner.com",
        "vatId": "TB211145123",
        "icon": "bx-trending-up",
        "color": "success"
    },
    {
        "id": 11,
        "type": "down",
        "transactionID": "#TBSC320003203",
        "amount": "$745.02",
        "img": "assets/images/ecommerce/payment/discover.png",
        "paymentMethod": "Discover",
        "transactionDate": "07 Jan, 2023",
        "status": "Pending",
        "clientName": "Howard Oneal",
        "clientEmail": "porttitor.tellus.non@yahoo.net",
        "vatId": "TB211146424",
        "icon": "bx-trending-up",
        "color": "success"
    }
]
export { transaction }